mollie/mollie-api-ruby

mollie.gemspec

Closes https://github.com/mollie/mollie-api-ruby/issues/10
Since restclient had a recent vulnerability, the _mollie-api-ruby_ gem prevented it from updating to the latest version. This PR fixes the set dependency so a more recent version can be installed.
@paetor PR as requested ;)

Update rest-client to a recent version

---

.gitignore
Gemfile
lib/Mollie/API/Client.rb
lib/Mollie/API/Client/Version.rb
mollie.gemspec

mollie.gemspec `import`ed Mollie/API/Client, which then did `require "rest_client"`. This is effectively a circular reference as it’s the gemspec file that indicates this gem is required, and in a clean gemset
where rest-client is not installed the gem cannot be built.
This fix moves the version constant into a separate file with no requirements of its own and references that from the gemspec, preserving the existing API but removing the circular reference.
I’ve also added a Gemfile to make it easier to install the required dependencies for working on the gem.

Fix reference to potentially missing gems from gemspec

---

lib/Mollie/API/Client.rb
lib/Mollie/API/Exception.rb

The API status codes are [well documented](https://www.mollie.com/en/docs/errors#alle-mogelijke-statuscodes) however the API library currently discards the status code. This change captures the HTTP code and returns it on the raised error.
Having this status available is important to allow callers to distinguish between cases such as a payment not being found, credentials being invalid, or the gateway being down.

Adds HTTP error code to raised errors

---

README.mdown
lib/Mollie/API/Client.rb
lib/Mollie/API/Object/Payment.rb

Following issue #16, this adds a couple of Rubyesque method aliases to `Mollie::API::Client` and `Mollie::API::Object::Payment`. 
I also took the liberty of updating the README by using Ruby Style Guide conventions in the code examples. Reason for doing this is to help other Ruby developers understand the API client code more easily.
Some suggestions for future improvements (not included in this PR, only noticed while working on it):
* Start writing automated unit and feature tests using either [RSpec](http://rspec.info/) or [minitest](https://github.com/seattlerb/minitest) (both have pros and cons). Having a test suite is something Ruby developers generally consider as a necessity nowadays.
* Include an automatic code style checker, such as [RuboCop](https://github.com/bbatsov/rubocop). …

Rubyesque aliases

---

lib/Mollie/API/Client.rb

The members `customers` and `customers_payments` weren't made public.

Make `customers` and `customers_payments` public

---

lib/Mollie/API/Object/Payment.rb

This added `refunded?` method to the payment so you can more easily check the status.

Added refunded? to Payments so that you can check the status.

---

README.mdown
mollie.gemspec

After installing the mollie-api-ruby gem I was not able to use the API, due to an "undefined method `[]' for #<Set: {#<MIME::Type: application/json>}>" error. I found out it was because of my version of mime-types (3.1).
This fix forces the use of mime-types < v3
See also: https://twitter.com/RogiervdBerg/status/768184731284414466
Version 2.99 of mime-types is still supported as 2.99.x, receiving quarterly updates of the IANA registry and security updates for two years. It will reach full end of life on 2017-11-21.

Add dependency for mime-types v <3

---

lib/mollie/api/client.rb
lib/mollie/api/resource/base.rb
test/mollie/api/resource/base_test.rb

Currently there is no way of setting an offset and a limit when retrieving all records. This add the offset and limit query params to the all method.

Add limit & offset to all method

---

lib/mollie/api/object/payment.rb
test/mollie/api/object/payment_test.rb

Allow for users to call
```Ruby 
payment.failed?
payment.pending?
payment.charged_back?
```
Instead of actually having to check the status.

Expose the failed status for a payment.

---

lib/mollie/api/object/organization.rb

It seems the organization registration datetime can be nil. I don't know what exactly causes it but not controlling this situation during the parsing phase is breaking the code.

Rescue nil registration datetime

---

lib/mollie/api/resource/base.rb

The `get` and `list` endpoints for payments accepts extra query strings to indicate if the payment was created in testmode or not. Also OAuth authorizations may need to filter by profileID.
- https://www.mollie.com/en/docs/reference/payments/get#pfp-params
- https://www.mollie.com/en/docs/reference/payments/list#pfp-params

Pass "options" array to retrieval methods

---

lib/mollie/api/object/issuer.rb

I expected these attributes to be available on the Issuer object directly which is more in line with the JSON response.

Add image and resource accessors to Mollie::API::Object::Issuer

---

lib/mollie/method.rb

It's possible to get a list of available payment methods by passing the `include` option:
```ruby
methods = ::Mollie::Method.all(
api_key: get_preference(:api_key),
include: 'issuers'
)
```
We currently don't allow accessing `methods.issuers` since it's missing from the `attr_accessor`.

Add issuers attr_accessor

---

.travis.yml

- Updated Rubygems secret.
- Added some additional information that's also set configured in https://github.com/mollie/spree-mollie-gateway/blob/master/.travis.yml (deployment works there).
I'll test if it works by creating a `4.0.0-alpha.2` tag (and update `version.rb`) once this is merged into master.

Renew Rubygems secret. Add additional deployment information.

---

.travis.yml

This will prevent Travis from trying to deploy on every tag.
From: https://docs.travis-ci.com/user/deployment#Examples-of-Conditional-Deployment
Also updated the secret, since previous one didn't work.

Only deploy when a tag is set and the Ruby version is 2.3.0 and update secret

---

lib/mollie/exception.rb

closes: mollie/mollie-api-ruby#90

Mollie::RequestError should inherit from Mollie::Exception

---

lib/mollie/client.rb
lib/mollie/customer/subscription.rb
test/fixtures/subscriptions/get.json
test/fixtures/subscriptions/get_payments.json
test/mollie/customer/subscription_test.rb

Add helper to fetch subscription payments

---

lib/mollie/client.rb
lib/mollie/exception.rb
test/mollie/client_test.rb

This makes it easier to solely rescue 404s. Resolves #128.

Raise specific exception when resource does not exist

---

lib/mollie/payment/capture.rb
test/mollie/payment/capture_test.rb

Fetch the Shipment resource using the hal+json `_links` href.
Resolves #106

Fix `Capture#shipment` API call

---

lib/mollie/onboarding.rb
test/fixtures/onboarding/me.json

This fixes the dashboard URL for onboarding, which should be `dashboard`, not `onboarding`.

Fix onboarding dashboard URL.

---

lib/mollie/list.rb
test/fixtures/customer/get.json
test/fixtures/customer/list-payments-next.json
test/fixtures/customer/list-payments.json
test/mollie/list_test.rb

Use the next and previous `_links` in the pagination logic.
Previously, pagination calls to a nested resource were incorrectly scoped.
For, example:
payments = customer.payments(limit: 2)
payments.next
The first line correctly retrieves:
/v2/customers/cst_8wmqcHMN4U/payments?from=tr_3&limit=2
The second line incorrectly called:
/v2/payments?from=tr_3&limit=2 (customer scope omitted)
Resolves #144

fix: Include parent resource in pagination calls

---

lib/mollie/method.rb
test/fixtures/methods/all.json
test/mollie/method_test.rb

Returns all payment methods that Mollie offers and can be activated by
the Organization.
Resolves #146, resolves #149

Add "List all payment methods" API

---

lib/mollie/base.rb
test/mollie/base_test.rb

Yesterday, there was a major disruption in mollie. I found out that some payments were created, but we didn't get a response back. Later on, we did get a webhook calllback though. 
The issue we encountered is that when you do a `get` without an ID, you get a collection of payments as a response. This cannot be mapped to the object (Payment), but yields an 'empty' Payment object anyway. However, this also means that if you call `chargebacks` on that object, that you receive a collection of all available chargebacks for the account. This had some unfortunate consequences for us :)

Ensure base get always receives an ID

---

lib/mollie/client.rb
lib/mollie/exception.rb
test/mollie/exception_test.rb

Useful when more information is needed by the user, such as the Retry-After header.
Closes #165

Add HTTP response details to RequestError

---

mollie-api-ruby.gemspec

Supported here: https://guides.rubygems.org/specification-reference/#metadata Useful for running https://github.com/MaximeD/gem_updater

Add changelog_uri to gemspec

---

examples/connect/authorize.rb
examples/connect/tokens.rb

The authorize URL changed from www.mollie.com to my.mollie.com. This is to reflect this change.

IMP-610: Use correct authorize URL

---

README.md

The issue has been resolved, and all gem releases are now available on RubyGems. To avoid misleading new users, we should remove this paragraph from the README and update the code sample accordingly.

Update README to reflect that all recent gems are available through RubyGems

---

lib/mollie/client.rb

Strings are not frozen, so we get these wanrings when running our test suite:
```
ruby/gems/3.4.0/gems/mollie-api-ruby-4.15.0/lib/mollie/client.rb:54: warning: literal string will be frozen in the future (run with --debug-frozen-string-literal for more information)
ruby/gems/3.4.0/gems/mollie-api-ruby-4.15.0/lib/mollie/client.rb:53: warning: literal string will be frozen in the future (run with --debug-frozen-string-literal for more information)
```

Avoid frozen string literals warnings with Ruby 3.4

---

lib/mollie/payment.rb
test/fixtures/payments/get_embedded_resources.json
test/mollie/payment_test.rb

In the API it's possible to embed refunds, so it's not necessary to do another request for them. In this PR I'm adding support for using this embedded refunds when doing something like `payment.refunds`.
The same needs to be done for chargebacks and captures. Maybe someone can help with adding those resources to `test/fixtures/payments/get_embedded_resources.json`

Add support for embedded refunds in payment object

---

lib/mollie/client.rb
lib/mollie/payment.rb
test/mollie/payment_test.rb

Payment: add release payment authorization API
