lib/Mollie/API/Object/Customer.rb
copy paste mistake I guess
The error I'm getting is
"superclass mismatch for class Payment"
=> remove Payment class

lib/Mollie/API/Resource/Customers/Subscriptions.rb
=> Parent_id should be class reference

lib/mollie/api/client.rb, lib/mollie/api/object/base.rb, lib/mollie/api/object/customer.rb, lib/mollie/api/object/issuer.rb, lib/mollie/api/object/list.rb, lib/mollie/api/object/mandate.rb, lib/mollie/api/object/method.rb, lib/mollie/api/object/payment.rb, lib/mollie/api/object/payment/refund.rb, lib/mollie/api/object/subscription.rb
Added all the properties and applying conversion for: 
- amounts using BigDecimal to avoid floating point issues.
- details using OpenStruct
- datetime using Time
I'm aware that I could use meta programming to maybe reduce the LOC in the Payment object, however I explicitly chose not to do this for easier maintenance by non-ruby programmers.
Next up is writing tests!
=> added all properties and apply conversion if possible

lib/mollie/api/util.rb, test/mollie/api/util_test.rb
paired with benoist, original author of this code to fix issue with nested hashes in Util#nested_underscore_keys.
also added Util in Mollie::API namespace so it doesn't pollute the global namespace.
=> fixes Util#nested_underscore_keys failure case (and tests for it)

website-docs/organisations/get.rb, website-docs/payments/get-refund.rb, website-docs/payments/payment-webhook.rb
2 new cases for the website-docs.
Also included a missing require on the organisations get.
=> Update the website documentation. Closes #72

website-docs/customers/create.rb
=> Mollie API does not accept en but instead accepts en_US

docs/migration_v2_2_x.md
Corrected key name for amount in the documentation for V2.2.x migration
=> Updated key name in migration_v2_2_x.md

lib/mollie/customer/subscription.rb, lib/mollie/payment.rb, test/mollie/customer/subscription_test.rb, test/mollie/payment_test.rb
=> Minor API changes

.travis.yml, examples/subscriptions/create.rb, lib/mollie/customer/subscription.rb, test/mollie/customer/subscription_test.rb
=> Add metadata attribute to Mollie::Customer::Subscription

.travis.yml, mollie-api-ruby.gemspec
=> Drop support for EOL versions of Ruby

lib/mollie/method.rb
=> Add P24 (przelewy24) payment method

CHANGELOG.md, README.md, lib/mollie/method.rb, lib/mollie/version.rb, mollie-api-ruby.gemspec
Can be merged on the 1st of May, 2019.
=> Remove Bitcoin

lib/mollie/customer/subscription.rb, test/mollie/customer/subscription_test.rb
=> Subscription: add `applicationFee` attribute

lib/mollie/customer/subscription.rb
=> Subscription: Add `links` helper method

lib/mollie/customer/mandate.rb, lib/mollie/customer/subscription.rb, lib/mollie/method.rb, lib/mollie/order/line.rb, lib/mollie/organization.rb, test/fixtures/orders/create.json, test/fixtures/orders/get.json, test/mollie/customer/mandate_test.rb, test/mollie/method_test.rb, test/mollie/order_test.rb, test/mollie/organization_test.rb
Implement various API features from the changelog up to Wednesday, March 27th, 2019.
=> Changelog updates

examples/onboarding/get.rb, examples/onboarding/submit.rb, lib/mollie.rb, lib/mollie/onboarding.rb, test/fixtures/onboarding/me.json, test/fixtures/onboarding/submit.json, test/mollie/onboarding_test.rb
=> Add Onboarding API

lib/mollie/method.rb, lib/mollie/order.rb, lib/mollie/payment.rb, test/fixtures/methods/get-includes-pricing.json, test/fixtures/orders/get.json, test/fixtures/payments/get.json, test/mollie/method_test.rb, test/mollie/order_test.rb, test/mollie/payment_test.rb
Implement API features and changes from the changelog up to and including Friday, January 17, 2020.
=> 2020-01: Changelog updates

lib/mollie/organization.rb, test/fixtures/shipments/get.json, test/mollie/organization_test.rb, test/mollie/settlement_test.rb
Implement API features and changes from the changelog up to and including Friday, April 3rd, 2020.
=> 2020-04: Changelog updates

examples/orders/update-orderline.rb, lib/mollie/order/line.rb, test/fixtures/orders/update_line.json, test/mollie/order/line_test.rb
=> fix: orderline update returns incorrect class

.travis.yml
https://github.com/mollie/mollie-api-ruby/issues/140
Updated Rubygems secret.
=> SEC-560 | add new (scoped) Rubygems API key

lib/mollie/order.rb, lib/mollie/payment.rb, test/fixtures/orders/get.json, test/mollie/order_test.rb, test/mollie/payment_test.rb
=> Add cancel_url attributes

lib/mollie/client.rb, test/mollie/client_test.rb
=> Add support for idempotency keys

examples/terminals/get.rb, examples/terminals/list.rb, lib/mollie.rb, lib/mollie/terminal.rb, test/fixtures/terminals/get.json, test/fixtures/terminals/list.json, test/mollie/terminal_test.rb
https://docs.mollie.com/reference/v2/terminals-api/overview (beta)
=> Add Terminals API

lib/mollie/method.rb
Updating the list of payment methods that are currently generally available
=> Update supported payment methods
